CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	
	[FirstName] VARCHAR(50) NOT NULL,
	
	[LastName] VARCHAR(50) NOT NULL,

	[Email] VARCHAR(50) NOT NULL,
	
	[Telephone] VARCHAR(50) NOT NULL,
	
	[JobRole] VARCHAR(50) NOT NULL
)
